"""first version

Revision ID: b6023a5e2604
Revises: 
Create Date: 2019-04-22 16:53:31.483869

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


# revision identifiers, used by Alembic.
revision = 'b6023a5e2604'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('app_user',
    sa.Column('yandex_id', sa.String(length=64), nullable=False),
    sa.Column('username', sa.String(length=32), nullable=True),
    sa.Column('json_filename', sa.String(length=128), nullable=True),
    sa.Column('location', sqlalchemy_utils.types.json.JSONType(), nullable=True),
    sa.PrimaryKeyConstraint('yandex_id')
    )
    op.create_table('search_request',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('potential_paths', sqlalchemy_utils.types.json.JSONType(), nullable=True),
    sa.Column('available_specifying_options', sqlalchemy_utils.types.json.JSONType(), nullable=True),
    sa.Column('comparison_depth', sa.SmallInteger(), nullable=True),
    sa.Column('app_user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['app_user_id'], ['app_user.yandex_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('search_request')
    op.drop_table('app_user')
    # ### end Alembic commands ###
